import { createFileRoute, Link } from "@tanstack/react-router";
import { Button } from "~/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/card";
import Container from "~/components/ui/container";

export const Route = createFileRoute("/")({
	component: Home,
});

function Home() {
	return (
		<Container size="lg">
			<header className="py-12 text-center">
				<h1 className="text-4xl md:text-5xl font-extrabold mb-4">
					FitFinder — AI resume matching
				</h1>
				<p className="text-muted-foreground max-w-2xl mx-auto mb-6">
					Upload resumes, compare against job descriptions, and get match scores
					and interview questions generated by AI.
				</p>
				<div className="flex justify-center gap-4">
					<Link to="/apply">
						<Button size="lg">Get Started</Button>
					</Link>
				</div>
			</header>

			<section className="grid md:grid-cols-3 gap-6 my-8">
				<Card>
					<CardHeader>
						<CardTitle>Fast Screening</CardTitle>
					</CardHeader>
					<CardContent>
						Analyze resumes quickly and get a clear match score and
						justification so you can shortlist faster.
					</CardContent>
				</Card>

				<Card>
					<CardHeader>
						<CardTitle>AI Generated Questions</CardTitle>
					</CardHeader>
					<CardContent>
						Receive tailored interview questions for each candidate to guide
						your interviews.
					</CardContent>
				</Card>

				<Card>
					<CardHeader>
						<CardTitle>Multi-Org Support</CardTitle>
					</CardHeader>
					<CardContent>
						Manage organizations, jobs, and resumes across teams with admin
						controls and permissions.
					</CardContent>
				</Card>
			</section>

			<section className="my-12 text-center">
				<Card className="inline-block">
					<CardContent>
						<h3 className="text-lg font-semibold mb-2">
							Ready to screen smarter?
						</h3>
						<div className="flex gap-3 justify-center">
							<Link to="/apply">
								<Button>Start a Free Analysis</Button>
							</Link>
						</div>
					</CardContent>
				</Card>
			</section>
		</Container>
	);
}
