/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedUploadRouteImport } from './routes/_authed/upload'
import { Route as AuthedOrganizationsRouteImport } from './routes/_authed/organizations'
import { Route as AuthedApplyRouteImport } from './routes/_authed/apply'
import { Route as AuthedUploadFnRouteImport } from './routes/_authed/upload.fn'
import { Route as AuthedOrganizationOrgIdRouteImport } from './routes/_authed/organization.$orgId'
import { Route as AuthedApplyFnRouteImport } from './routes/_authed/apply.fn'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUploadRoute = AuthedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrganizationsRoute = AuthedOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApplyRoute = AuthedApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUploadFnRoute = AuthedUploadFnRouteImport.update({
  id: '/fn',
  path: '/fn',
  getParentRoute: () => AuthedUploadRoute,
} as any)
const AuthedOrganizationOrgIdRoute = AuthedOrganizationOrgIdRouteImport.update({
  id: '/organization/$orgId',
  path: '/organization/$orgId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApplyFnRoute = AuthedApplyFnRouteImport.update({
  id: '/fn',
  path: '/fn',
  getParentRoute: () => AuthedApplyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/apply': typeof AuthedApplyRouteWithChildren
  '/organizations': typeof AuthedOrganizationsRoute
  '/upload': typeof AuthedUploadRouteWithChildren
  '/apply/fn': typeof AuthedApplyFnRoute
  '/organization/$orgId': typeof AuthedOrganizationOrgIdRoute
  '/upload/fn': typeof AuthedUploadFnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/apply': typeof AuthedApplyRouteWithChildren
  '/organizations': typeof AuthedOrganizationsRoute
  '/upload': typeof AuthedUploadRouteWithChildren
  '/apply/fn': typeof AuthedApplyFnRoute
  '/organization/$orgId': typeof AuthedOrganizationOrgIdRoute
  '/upload/fn': typeof AuthedUploadFnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authed/apply': typeof AuthedApplyRouteWithChildren
  '/_authed/organizations': typeof AuthedOrganizationsRoute
  '/_authed/upload': typeof AuthedUploadRouteWithChildren
  '/_authed/apply/fn': typeof AuthedApplyFnRoute
  '/_authed/organization/$orgId': typeof AuthedOrganizationOrgIdRoute
  '/_authed/upload/fn': typeof AuthedUploadFnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/apply'
    | '/organizations'
    | '/upload'
    | '/apply/fn'
    | '/organization/$orgId'
    | '/upload/fn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/apply'
    | '/organizations'
    | '/upload'
    | '/apply/fn'
    | '/organization/$orgId'
    | '/upload/fn'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/apply'
    | '/_authed/organizations'
    | '/_authed/upload'
    | '/_authed/apply/fn'
    | '/_authed/organization/$orgId'
    | '/_authed/upload/fn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/upload': {
      id: '/_authed/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthedUploadRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/organizations': {
      id: '/_authed/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthedOrganizationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/apply': {
      id: '/_authed/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof AuthedApplyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/upload/fn': {
      id: '/_authed/upload/fn'
      path: '/fn'
      fullPath: '/upload/fn'
      preLoaderRoute: typeof AuthedUploadFnRouteImport
      parentRoute: typeof AuthedUploadRoute
    }
    '/_authed/organization/$orgId': {
      id: '/_authed/organization/$orgId'
      path: '/organization/$orgId'
      fullPath: '/organization/$orgId'
      preLoaderRoute: typeof AuthedOrganizationOrgIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/apply/fn': {
      id: '/_authed/apply/fn'
      path: '/fn'
      fullPath: '/apply/fn'
      preLoaderRoute: typeof AuthedApplyFnRouteImport
      parentRoute: typeof AuthedApplyRoute
    }
  }
}

interface AuthedApplyRouteChildren {
  AuthedApplyFnRoute: typeof AuthedApplyFnRoute
}

const AuthedApplyRouteChildren: AuthedApplyRouteChildren = {
  AuthedApplyFnRoute: AuthedApplyFnRoute,
}

const AuthedApplyRouteWithChildren = AuthedApplyRoute._addFileChildren(
  AuthedApplyRouteChildren,
)

interface AuthedUploadRouteChildren {
  AuthedUploadFnRoute: typeof AuthedUploadFnRoute
}

const AuthedUploadRouteChildren: AuthedUploadRouteChildren = {
  AuthedUploadFnRoute: AuthedUploadFnRoute,
}

const AuthedUploadRouteWithChildren = AuthedUploadRoute._addFileChildren(
  AuthedUploadRouteChildren,
)

interface AuthedRouteChildren {
  AuthedApplyRoute: typeof AuthedApplyRouteWithChildren
  AuthedOrganizationsRoute: typeof AuthedOrganizationsRoute
  AuthedUploadRoute: typeof AuthedUploadRouteWithChildren
  AuthedOrganizationOrgIdRoute: typeof AuthedOrganizationOrgIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedApplyRoute: AuthedApplyRouteWithChildren,
  AuthedOrganizationsRoute: AuthedOrganizationsRoute,
  AuthedUploadRoute: AuthedUploadRouteWithChildren,
  AuthedOrganizationOrgIdRoute: AuthedOrganizationOrgIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
